import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
	title: "Github Finder",
	description: "Generated by create next app",
};

const poppins = Poppins({
	subsets: ["latin"],
	weight: ["400", "500", "700"],
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`${poppins.className} bg-gradient-to-t from-gray-700`}
		>
			<body>{children}</body>
		</html>
	);
}
